spring.application.name=githubproxy
spring.cloud.openfeign.client.config.gitRepositoryPlaceholder.url=https://api.github.com/
spring.cloud.openfeign.circuitbreaker.enabled=true
logging.level.com.microservice.client=DEBUG
spring.cloud.openfeign.client.config.gitRepositoryPlaceholder.loggerLevel=FULL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/compose-postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:Piotr}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
logging.level.root=INFO
